import React, { useState } from "react";
import { useApp } from "../context/AppContext";

export default function EventTypesTemplates() {
  const { eventTypes, addEventType, updateEventType, deleteEventType, addTodoTask, deleteTodoTask, eventEmoji, arabicLabel } = useApp();
  const [name, setName] = useState("");
  const [newTasks, setNewTasks] = useState({});
  const submit = (e) => { e.preventDefault(); addEventType(name); setName(""); };
  const addTask = (typeId) => { addTodoTask(typeId, newTasks[typeId] || ""); setNewTasks((prev) => ({ ...prev, [typeId]: "" })); };
  return (
    <div className="space-y-6 pb-12 text-white" dir="rtl">
      <div className="rounded-3xl border border-blue-400/20 bg-blue-500/10 p-6"><h1 className="text-3xl font-black bg-clip-text text-transparent bg-gradient-to-r from-blue-300 to-white">🗂️ أنواع المناسبات وقوالب المهام</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-300">هذه الصفحة تضبط أنواع المناسبات وقوائم المهام التي تظهر في تطبيق العميل بعد الحجز. كل مناسبة لها قائمة خاصة، وأي مهمة تضيفها هنا تظهر في التطبيق.</p></div>
      <form onSubmit={submit} className="salora-section-card p-6"><h3 className="mb-3 font-black text-blue-300">➕ إضافة نوع مناسبة جديد</h3><div className="grid gap-3 md:grid-cols-[1fr_180px]"><input className="field-surface" value={name} onChange={(e) => setName(e.target.value)} placeholder="مثال: معرض، ورشة عمل..." /><button className="rounded-2xl bg-blue-600 px-5 py-3 font-black text-white hover:bg-blue-500">إضافة النوع</button></div></form>
      <div className="grid grid-cols-1 gap-5 xl:grid-cols-2">{eventTypes.map((type) => (<div key={type.id} className="salora-section-card p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-xs font-bold tracking-widest text-blue-300">نوع المناسبة</div><h3 className="mt-1 text-2xl font-black">{eventEmoji?.[type.name] || "🎯"} {arabicLabel(type.name)}</h3><p className="mt-1 text-xs text-slate-500">هذه القائمة ترسل إلى تطبيق العميل عند اختيار هذه المناسبة.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => updateEventType(type.id, { status: type.status === "Active" ? "Disabled" : "Active" })} className={`rounded-xl px-4 py-2 text-xs font-bold ${type.status === "Active" ? "bg-emerald-500/15 text-emerald-300" : "bg-red-500/15 text-red-300"}`}>{arabicLabel(type.status)}</button><button onClick={() => deleteEventType(type.id)} className="rounded-xl bg-red-500/15 px-4 py-2 text-xs font-bold text-red-300">حذف</button></div></div><div className="mt-5 grid gap-2">{(type.todo || []).map((task, index) => (<div key={`${type.id}-${index}`} className="flex items-center justify-between gap-3 rounded-2xl border border-white/10 bg-slate-950/40 p-3 text-sm text-slate-300"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-blue-500/15 text-xs font-black text-blue-300">{index + 1}</span><span>{task}</span></div><button onClick={() => deleteTodoTask(type.id, index)} className="rounded-xl bg-red-500/15 px-3 py-2 text-xs font-bold text-red-300">إزالة</button></div>))}</div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_120px]"><input className="field-surface" value={newTasks[type.id] || ""} onChange={(e) => setNewTasks((prev) => ({ ...prev, [type.id]: e.target.value }))} placeholder="أضف مهمة جديدة لهذه المناسبة..." /><button onClick={() => addTask(type.id)} className="rounded-xl bg-blue-600 px-4 py-3 text-xs font-black text-white hover:bg-blue-500">إضافة</button></div></div>))}</div>
    </div>
  );
}
