import React, { useEffect, useState } from "react";
import { apiClient } from "../services/apiClient";
import { resolveMediaUrl } from "../utils/mediaUrl";

export default function PaymentMethodsManagement() {
  const [items,setItems]=useState([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const load=async()=>{setBusy(true);try{setItems(await apiClient.get('/admin/payment-methods'));}catch(e){setMessage(e.message);}finally{setBusy(false);}};
  useEffect(()=>{load();},[]);
  const save=async(item,file)=>{setMessage("");const form=new FormData();['name_ar','name_en','instructions','sort_order'].forEach(k=>form.append(k,item[k]??''));form.append('for_venues',item.for_venues?'1':'0');form.append('for_providers',item.for_providers?'1':'0');form.append('is_active',item.is_active?'1':'0');if(file)form.append('logo',file);try{await apiClient.post(`/admin/payment-methods/${item.id}`,form);setMessage('تم حفظ وسيلة الدفع.');await load();}catch(e){setMessage(e.message);}};
  const update=(id,key,value)=>setItems(v=>v.map(x=>x.id===id?{...x,[key]:value}:x));
  return <div className="space-y-6 pb-12 text-white" dir="rtl"><div><h1 className="text-3xl font-black">💳 وسائل الدفع</h1><p className="mt-2 text-sm text-slate-400">الوسائل المسموحة فقط: شام كاش، سيريتل كاش، والهرم. تستطيع رفع الشعار الرسمي وتغيير التعليمات والحالة.</p></div>{message&&<div className="rounded-2xl border border-blue-400/20 bg-blue-500/10 p-4 text-sm">{message}</div>}{busy?<div>جاري التحميل...</div>:<div className="grid gap-5 lg:grid-cols-3">{items.map(item=><MethodCard key={item.id} item={item} update={update} save={save}/>)}</div>}</div>;
}
function MethodCard({item,update,save}){const [file,setFile]=useState(null);return <div className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="mb-4 flex items-center gap-3">{item.logo_url||item.logo_path?<img src={resolveMediaUrl(item.logo_url||item.logo_path)} className="h-14 w-20 rounded-xl bg-white object-contain p-2"/>:<div className="grid h-14 w-20 place-items-center rounded-xl bg-white/5">💳</div>}<div><div className="font-black">{item.name_ar}</div><div className="text-xs text-slate-500">{item.slug}</div></div></div><label className="mb-1 block text-xs text-slate-400">الاسم العربي</label><input className="field-surface mb-3 w-full" value={item.name_ar||''} onChange={e=>update(item.id,'name_ar',e.target.value)}/><label className="mb-1 block text-xs text-slate-400">التعليمات</label><textarea className="field-surface mb-3 min-h-28 w-full" value={item.instructions||''} onChange={e=>update(item.id,'instructions',e.target.value)}/><label className="mb-3 flex cursor-pointer items-center gap-2 rounded-xl border border-white/10 p-3"><input type="file" accept="image/*,.svg" onChange={e=>setFile(e.target.files?.[0]||null)}/><span className="text-xs">رفع الشعار الرسمي</span></label><div className="mb-4 flex flex-wrap gap-3 text-xs"><label><input type="checkbox" checked={!!item.for_venues} onChange={e=>update(item.id,'for_venues',e.target.checked)}/> للصّالات</label><label><input type="checkbox" checked={!!item.for_providers} onChange={e=>update(item.id,'for_providers',e.target.checked)}/> لمقدمي الخدمات</label><label><input type="checkbox" checked={!!item.is_active} onChange={e=>update(item.id,'is_active',e.target.checked)}/> فعالة</label></div><button onClick={()=>save(item,file)} className="w-full rounded-xl bg-blue-600 py-3 font-black hover:bg-blue-500">حفظ</button></div>}
