import React, { useMemo, useState } from "react";
import { useApp } from "../context/AppContext";

const statusClass = { Approved: "bg-emerald-500/15 text-emerald-300 border-emerald-400/20", Pending: "bg-amber-500/15 text-amber-300 border-amber-400/20", Rejected: "bg-red-500/15 text-red-300 border-red-400/20" };

export default function VenuesManagement() {
  const { venues, adminActionVenue, formatPricePair, setGlobalViewVenue, arabicLabel } = useApp();
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All");
  const filteredVenues = useMemo(() => venues.filter((venue) => {
    const haystack = [venue.name, venue.owner, venue.city, venue.status].join(" ").toLowerCase();
    return haystack.includes(query.toLowerCase()) && (status === "All" || venue.status === status);
  }), [venues, query, status]);
  return (
    <div className="space-y-6 pb-12 text-white" dir="rtl">
      <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h1 className="text-3xl font-black bg-clip-text text-transparent bg-gradient-to-r from-blue-300 to-white">🏛️ إدارة الصالات</h1><p className="mt-2 text-sm text-slate-400">الأدمن يراجع الصالات ويشاهد تفاصيلها قبل القبول أو الرفض. الصالات المقبولة فقط تظهر في تطبيق العملاء.</p></div><div className="grid w-full max-w-xl gap-3 md:grid-cols-[1fr_180px]"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ابحث عن صالة أو مالك أو مدينة..." className="field-surface" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="field-surface"><option value="All">كل الحالات</option><option value="Approved">مقبولة</option><option value="Pending">قيد المراجعة</option><option value="Rejected">مرفوضة</option></select></div></div>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="text-xs text-slate-500">إجمالي الصالات</div><div className="mt-1 text-2xl font-black">{filteredVenues.length}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="text-xs text-slate-500">مقبولة</div><div className="mt-1 text-2xl font-black text-emerald-300">{filteredVenues.filter((v) => v.status === "Approved").length}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><div className="text-xs text-slate-500">قيد المراجعة</div><div className="mt-1 text-2xl font-black text-amber-300">{filteredVenues.filter((v) => v.status === "Pending").length}</div></div></div>
      <div className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.04]"><div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-right text-sm"><thead className="bg-slate-950/50 text-xs text-blue-300"><tr><th className="px-5 py-4">الصالة</th><th className="px-5 py-4">المالك</th><th className="px-5 py-4">السعة</th><th className="px-5 py-4">أنواع المناسبات</th><th className="px-5 py-4">السعر النهائي</th><th className="px-5 py-4 text-center">الحالة</th><th className="px-5 py-4 text-center">الإجراءات</th></tr></thead><tbody>{filteredVenues.map((venue) => (<tr key={venue.id} className="border-t border-white/5 hover:bg-white/[.03]"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="h-14 w-20 overflow-hidden rounded-xl bg-slate-900">{venue.imageUrls?.[0] ? <img src={venue.imageUrls[0]} alt={venue.name} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center">🏛️</div>}</div><div><div className="font-black text-white">{venue.name}</div><div className="text-xs text-slate-500">{venue.city} • {venue.address}</div></div></div></td><td className="px-5 py-4 text-slate-300">{venue.owner}</td><td className="px-5 py-4 text-slate-300">{venue.capacity} ضيف</td><td className="px-5 py-4 text-xs text-slate-400">{(venue.supportedEventTypes || []).map(arabicLabel).join(" • ")}</td><td className="px-5 py-4 font-bold text-emerald-300">{formatPricePair(venue.finalPrice || venue.basePrice)}</td><td className="px-5 py-4 text-center"><span className={`rounded-full border px-3 py-1 text-[11px] font-black ${statusClass[venue.status] || statusClass.Pending}`}>{arabicLabel(venue.status)}</span></td><td className="px-5 py-4"><div className="flex flex-wrap justify-center gap-2"><button onClick={() => setGlobalViewVenue(venue)} className="rounded-lg bg-blue-500/15 px-3 py-2 text-xs font-bold text-blue-300">مشاهدة</button>{venue.status !== "Approved" && <button onClick={() => adminActionVenue(venue.id, "Approved")} className="rounded-lg bg-emerald-500/15 px-3 py-2 text-xs font-bold text-emerald-300">قبول</button>}{venue.status !== "Rejected" && <button onClick={() => adminActionVenue(venue.id, "Rejected")} className="rounded-lg bg-amber-500/15 px-3 py-2 text-xs font-bold text-amber-300">رفض</button>}<button onClick={() => adminActionVenue(venue.id, "delete")} className="rounded-lg bg-red-500/15 px-3 py-2 text-xs font-bold text-red-300">حذف</button></div></td></tr>))}</tbody></table></div></div>
    </div>
  );
}
